### ISSUE TITLE
macOS: Unable to select resources or artifacts archive

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/WPILibInstaller-Avalonia#115]
On macOS, it's not possible to select the resource or artifacts archives. They are greyed out.

![Screen Shot 2020-11-23 at 2 11 35 PM](https://user-images.githubusercontent.com/4885091/100021306-268c3800-2d96-11eb-9a23-11b1bd3a29f8.png)

**Comment by ThadHouse** [comment]
https://github.com/wpilibsuite/WPILibInstaller-Avalonia/blob/672b1771de29244d8392cafe7888729b88fdec38/WPILibInstaller-Avalonia/ViewModels/StartPageViewModel.cs#L222

Adding the extension restrictions here probably broke it.
