### ISSUE TITLE
Better handling of java process in use

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/WPILibInstaller-Avalonia#117]
Since the gradle daemon is likely to be running, the reinstalling java leads to an exception.

Potential solutions:

- Detect if the installed version of java is the same as the to be installed version, and skip. It seems like the release file in the jdk folder could be used for this.
- Kill any java processes using the frc jdk (probably dangerous, and possibly not OS agnostic)
- Catch the exception and display a better error message recommending a reboot

**Comment by PeterJohnson** [comment]
This is only an issue on Windows.

**Comment by Daltz333** [comment]
What exception is thrown?
