### ISSUE TITLE
Trouble Opening Existing Code

### ISSUE THREAD

**Issue by riverpease15** [wpilibsuite/WPILibInstaller-Avalonia#156]
I downloaded Visual Studio from the official Visual Studio website. I then uninstalled Visual Studio using the uninstall script and downloaded the WPILib installer. Everything seemed to go according to plan: I followed the process for "Download VS Code for Single Install" and opened VS. I then opened the folder containing my team's code and was confronted with lots of red-underline. WPILib was installed, but there were still errors.

After going through the uninstall then reinstall process four additional times, I decided I needed some help. I'm using a MacBook Pro for reference, and I think the issue has something to do with the software not being fully uninstalled between trials, but I'm not sure. Any help on this would be greatly appreciated! Thank you.

**Comment by prateekma** [comment]
Can you share a screenshot of the red underline errors?

**Comment by riverpease15** [comment]
There are errors with every .java file, but here's a screenshot inside Visual Studio with one of the files opened.

![Screen Shot 2021-01-18 at 12 13 55 PM](https://user-images.githubusercontent.com/41012306/104945389-aa256800-5986-11eb-9047-d8400c10474e.png)

**Comment by sciencewhiz** [comment]
Can you give more details about how the project was created initially? For example, if it was created with last yea's WPILib VS Code I wouldn't have expected to see a .classpath file. Did you follow the [import process](https://docs.wpilib.org/en/stable/docs/software/vscode-overview/importing-gradle-project.html)?

Does this happen if you create a new project?

Can you post the information provided by "WPILib: Show Project Information"

**Comment by riverpease15** [comment]
I received the project from a teammate who sent it to me as a zip file. I'm new to the team this year, and yes, all the code is from 2020. 

I didn't follow the import process (I didn't know it existed until now, lol), but I also didn't receive an error when opening the folder with the project in it.

Other .java files created in VS show no errors, but I haven't tried making a new robotics project in VS yet. (Again, I'm brand new and just trying to get access to the team's code).

I attached a screenshot of the information provided by "WPILib: Show Project Information". As you'll see, there isn't any.
<img width="1440" alt="Screen Shot 2021-01-19 at 11 22 06 AM" src="https://user-images.githubusercontent.com/41012306/105062788-ff29b280-5a48-11eb-9f0c-1f89ddd9a5df.png">

**Comment by sciencewhiz** [comment]
If you create a new example project, it will eliminate ambiguity as to whether the problem is with your teams project, or with your computers installation.

**Comment by riverpease15** [comment]
Okay, so I created a new sample project with no errors. My team sent the 2021 version of our code and I opened that and still received all the errors.

**Comment by riverpease15** [comment]
<img width="450" alt="Screen Shot 2021-01-22 at 11 15 54 AM" src="https://user-images.githubusercontent.com/41012306/105515859-34314180-5ca3-11eb-9ce5-5f3a825399e7.png">
I think this is the issue, I don't know how to solve it.

**Comment by ThadHouse** [comment]
That picture is showing you have the wrong folder open. You don't want to open the entire user folder in vscode like you have, but instead you only want to open the folder that contains build.gradle and the rest of the project files.
