### ISSUE TITLE
WPILIB Quits Unexpectedly During Installation on Mac

### ISSUE THREAD

**Issue by SahilP113** [wpilibsuite/WPILibInstaller-Avalonia#170]
I was attempting to download the newest version(2021.3.1) of WPILIB on my Mac (Intel, not M1). It allowed me to download the disk image, but when I opened the installer, MacOS(version 10.12.6) verified the installer, and it prompted me to open the app from the internet. When I clicked to open it, it said WPILib has quit unexpectedly. When I clicked on show details, it provided me with a long stack trace. 

I've attached it below:
[WPIInstaller Stack Trace.txt](https://github.com/wpilibsuite/WPILibInstaller-Avalonia/files/6651855/WPIInstaller.Stack.Trace.txt)

I also dragged the installer onto my desktop. When I opened the installer from my desktop, it said that the installer had been damaged.

**Comment by prateekma** [comment]
macOS 10.14 is the minimum supported version: https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-2/wpilib-setup.html

**Comment by SahilP113** [comment]
Thank you so much! I will download the new version.
