### ISSUE TITLE
Application freeze on installer files

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/WPILibInstaller-Avalonia#2]
![image](https://user-images.githubusercontent.com/10674555/78073132-4a65be00-736e-11ea-8cba-0d1c3c7a5e9b.png)

Causes the main thread to freeze, which on slow computers can cause windows to interpret it as "Not Responding"

**Comment by ThadHouse** [comment]
This is the installer files, not the resource files, right? They are very different.

**Comment by Daltz333** [comment]
Correct. Installer.

**Comment by ThadHouse** [comment]
This doesn't seem to happen anymore. Reopen if it does.
