### ISSUE TITLE
Use Python 3 on macOS

### ISSUE THREAD

**Issue by prateekma** [wpilibsuite/WPILibInstaller-Avalonia#203]
When the installer invokes Python, this popup displays on macOS 12.0.1 (Monterey):

<img width="273" alt="image" src="https://user-images.githubusercontent.com/19977330/142728969-eafd9e44-cb20-4758-8876-da923bbafa86.png">

The "Learn More..." button links to https://www.python.org/doc/sunset-python-2/

**Comment by sciencewhiz** [comment]
It appears that 10.15 and later has python3 available. We'd lose 10.14, but that just went out of support by Apple.
