### ISSUE TITLE
Installer does not run on Windows 8 laptop

### ISSUE THREAD

**Issue by Team-1493** [wpilibsuite/WPILibInstaller-Avalonia#245]
We are trying to install WPILib tools on an older laptop running windows 8.  We downloaded and mounted the disk image, but when I run the installer I get a spinning circle for a few seconds and then nothing.  No error message, doesn't freeze - it seems like it just quits.  

We updated the system software, including the update noted in WPILib, rebooted, and disabled the firewall with no success.  A snapshot of our system information is attached.

![Capture](https://user-images.githubusercontent.com/86333294/150638408-0fa2884b-f644-427c-b9a6-38bc2e229cd5.PNG)

**Comment by ThadHouse** [comment]
I'm not sure we will be able to solve this. Windows 8 has been out of support by Microsoft for years, as it was quickly replaced by windows 8.1. I'm guessing Windows 8 didn't get some updates that the installer requires to run. It's very difficult to even get a raw Windows 8 setup nowadays. We are dropping support for everything before Windows 10 next year anyway. I can try and see if I can figure it out, but I can't promise anything.

**Comment by sciencewhiz** [comment]
Closing as 2023 won't support anything earlier the Windows 10
