### ISSUE TITLE
No usable version of LibSSL found (Ubuntu 22.04 LTS)

### ISSUE THREAD

**Issue by big-harry** [wpilibsuite/WPILibInstaller-Avalonia#251]
I have installed libssl-dev and libssl3 and it still can't find them.

I installed them off the default jammy repositories.

**Comment by ThadHouse** [comment]
Because the installer is running .net 5, it will not work in 22.04, because 22.04 only includes openssl3 whereas .net 5 requires openssl1. This will be something fixed for 2023, but we won’t be releasing another update this season.
