### ISSUE TITLE
Button that leads to known issues and change log

### ISSUE THREAD

**Issue by itsmichaelyu** [wpilibsuite/WPILibInstaller-Avalonia#256]
A lot of teams are unaware about changes and issues with WPILib, so if two buttons were added to the end of the installer, one leading to a change log and another leading to the known issues page, people could be made aware that these pages exist.

**Comment by calcmogul** [comment]
We could even go so far as to automatically open a browser to those pages because our users won't read docs unless we make them. :grin:

Each OS has a browser-agnostic way to open web pages, iirc.
