### ISSUE TITLE
2023.1.1 Beta 2 macOS installer cannot be opened

### ISSUE THREAD

**Issue by lhvy** [wpilibsuite/WPILibInstaller-Avalonia#282]
**Describe the bug**
Just downloaded `WPILib_macOS-Arm64-2023.1.1-beta-2.dmg` as part of WPILib's beta testing task 1, and mounted the `.dmg` and tried to run the installer, only to be met with an error on launching the app (screenshot below). I have checked the md5 hash of my download and the download seems valid. I have also attempted the usual macOS "right-click > open" strategy to launch unrecognised apps, with no success.

**To Reproduce**
1. Download either macOS version of the 2023.1.1 Beta 2
2. Mount installer image and launch installer app

**Expected behavior**
Installer opens and runs successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/40507205/199498462-6358d3ca-cbc6-4812-9c2d-eb5caefc8192.png)

**Desktop (please complete the following information):**
 - WPILib Version: 2023.1.1 Beta 2
 - OS: macOS 13.0
 - Java version 11.0.16.1
 - C++ version N/A

**Comment by prateekma** [comment]
What happens when you extract the .app to your Downloads folder and then try the workaround? You still need the disk image mounted, but run the .app from outside of the disk image.

**Comment by lhvy** [comment]
Still no luck. I can try running `sudo xattr -d com.apple.quarantine /Users/Lucas/Downloads/WPILibInstaller.app` once the `.app` is extracted, which is way more than I usually need to get unsigned apps to open, certainly never had any issues with WPILib like this in the past, but then the app just crashes on launch with a generic error: 
<img width="272" alt="image" src="https://user-images.githubusercontent.com/40507205/199505229-39279b50-a11d-4849-9091-948ed78c44ab.png">

**Comment by prateekma** [comment]
That's interesting. I think the generic error is an actual issue with the installer; is there a stack trace? Having to remove the quarantine attribute is a temporary issue in beta because our Apple certificate expired and we are working on renewing for the official 2023 release.

**Comment by lhvy** [comment]
A quick download and test of the intel installer displays the same issue by the way. Just tested now on the same machine (M1 MacBook Pro running macOS Ventura 13.0)

**Comment by lhvy** [comment]
> That's interesting. I think the generic error is an actual issue with the installer; is there a stack trace? Having to remove the quarantine attribute is a temporary issue in beta because our Apple certificate expired and we are working on renewing for the official 2023 release.

Not sure exactly how to get the stack trace you want. Hopefully this is what you mean? https://pst.klgrth.io/paste/swa3a
