### ISSUE TITLE
Crash on Invalid ZIP

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/WPILibInstaller-Avalonia#3]
Selecting an Invalid ZIP file gives the following exception. The reasonable response would be to tell the user that the zip file is invalid and select a different zip file.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=WPILibInstaller_Avalonia
  StackTrace:
   at WPILibInstaller_Avalonia.ViewModels.StartPageViewModel.<SelectResourceFilesFunc>d__23.MoveNext() in C:\Users\Dalton Smith\Documents\WPILibInstaller-Avalonia\WPILibInstaller-Avalonia\ViewModels\StartPageViewModel.cs:line 95
```
On ``using (StreamReader reader = new StreamReader(entry.Open()))``

**Comment by ThadHouse** [comment]
This is the Resource one right? Definitely need more error handling, its one thing this doesn't do as well as the Forms based installer.

As a reminder, I also need to check that the installer one is valid too.

Note these buttons are only debug features. The actual published build will be like previous, where the zip is embedded. The old one had this as a debug feature too.

**Comment by Daltz333** [comment]
Yes. I was on the resource one, and then selected the main zip instead of the resource zip.

**Comment by ThadHouse** [comment]
Yeah. Won't matter much to the end user since they won't see the separate zips, but agreed it should be at least slightly better.

**Comment by ThadHouse** [comment]
This really isn't a problem, except when doing raw development.
