### ISSUE TITLE
Python does not ship with macOS

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/WPILibInstaller-Avalonia#319]
This breaks the tools installer.

Hotfix: Use ruby on macOS or bash on macos/linux
Warmfix: Per-platform executables

**Comment by TheTripleV** [comment]
Ruby (tested but not reviewed):
```ruby
#!/usr/bin/env ruby

require 'open3'

script_name = File.realpath(__FILE__)
jar_name = script_name.chomp(File.extname(script_name)) + '.jar'

jdk_dir = File.join(File.dirname(jar_name), '..', 'jdk', 'bin', 'java')

begin
  stdout, stderr, status = Open3.capture3("#{jdk_dir} -jar #{jar_name}")
  raise "Error launching tool:\n#{stderr}" unless status.success?
rescue
  # Start failed. Try JAVA_HOME.
  begin
    jdk_dir = File.join(ENV['JAVA_HOME'], 'bin', 'java')
  rescue
    # No JAVA_HOME. Try just running java from PATH.
    jdk_dir = 'java'
  end
  stdout, stderr, status = Open3.capture3("#{jdk_dir} -jar #{jar_name}")
  raise "Error launching tool:\n#{stderr}" unless status.success?
end

# Wait 3 seconds and print stdout/stderr if the process exits
3.times do
  sleep 1
  stdout, stderr, status = Open3.capture3("#{jdk_dir} -jar #{jar_name}")
  puts stdout
  STDERR.puts stderr
  break unless status.success?
end
```

**Comment by auscompgeek** [comment]
For posterity, the script to be replaced is https://github.com/wpilibsuite/WPILibInstaller-Avalonia/blob/7e36ad377828664d4758affe143d405cb24f5e35/files/ToolsUpdater.py

**Comment by ThadHouse** [comment]
All 3 scripts would actually need to be replaced there. And currently, these scripts are shared between linux and macos too. So there would be more work that would be necessary.

Also, if we change the extension, we'd need to update gradlerio and vscode. We'd also need to check if I launch the script as an executable, or as an argument to python in those cases (I don't remember).
