### ISSUE TITLE
segmentation fault when downloading VSCode Linux

### ISSUE THREAD

**Issue by nickquednow** [wpilibsuite/WPILibInstaller-Avalonia#332]
When installing WPILib VSCode (with the Linux version), if the adaptor is "connected," but does not have an internet connection (such as in virtualbox you have a bridged adaptor and it is to one that is not actively connected to anything), the WPILib installer produces a segmentation fault.

There was no log outputted due to the segmentation fault and it being a hard crash.

in case any of it matters:

Virtualbox version: 6.1.38 r153438
Ubuntu 22.04
1 thread
4GB of RAM
60GB hard disk

**Comment by ThadHouse** [comment]
Theres unlikely to be anything we can do to solve this. This is probably a crash in .NET somewhere.

**Comment by PeterJohnson** [comment]
We upgraded to .NET 8 for 2024.  Please reopen if this is still an issue in 2024.
