### ISSUE TITLE
Installing vscode completely offline

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/WPILibInstaller-Avalonia#335]
Currently the installer only supports installing offline using a .zip file the installer creates when it's run online.  This is problematic at events with poor internet where it's difficult to get a laptop connected to the internet while running the installer to download the installation files.  We should provide a way to install vscode or create the vscode zip file that does not require the full installer to be run.  E.g. provide a link on the releases page or documentation to get the correct version of the vscode platform zip/tgz and have the installer support installing directly from that rather than our custom packaged zip.

**Comment by sciencewhiz** [comment]
The CSA tool does not. I used the installer to create the Zip file and added it to my usb. 

Since we need different installers for different platforms, I think there's minimal benefit to having an all in one zip vs using the individual files, so I'd be in favor of this change.

**Comment by ThadHouse** [comment]
The benefit to the all in one zip is you don't need access to the other platforms as a CSA to download the right one. I will however make it so you can also use the stock zips as well, since I now have ways to detect those.
