### ISSUE TITLE
Next is available with no VSCode installed.

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/WPILibInstaller-Avalonia#4]
Should VSCode be optional?

**Comment by ThadHouse** [comment]
Right now I force it to true because I'm lazy. Its a one line fix here

https://github.com/ThadHouse/WPILibInstaller-Avalonia/blob/master/WPILibInstaller-Avalonia/ViewModels/VSCodePageViewModel.cs#L141

Just remove that line.

**Comment by ThadHouse** [comment]
This is handled the way we want to. Closing.
