### ISSUE TITLE
vscode command for setting JAVA_HOME does nothing on Linux

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/WPILibInstaller-Avalonia#40]
One of my students tried using the command to set JAVA_HOME a couple days ago on
Ubuntu 20.04. Before and after reopening the terminal, JAVA_HOME was still
empty.

**Comment by sciencewhiz** [comment]
VS Code terminal, or linux terminal? The command should only affect the VS Code terminal

**Comment by ThadHouse** [comment]
This bug would need to be in the vscode extension anyway. Its unrelated to the installer.

**Comment by ThadHouse** [comment]
Actually, the command doesn't actually do anything for the terminal. It sets the java directory for the gradle commands ran inside vscode. So its unrelated to this.
