### ISSUE TITLE
On macOS, the `java` executable included with WPILib doesn't have a code signature when updating

### ISSUE THREAD

**Issue by ajs256** [wpilibsuite/WPILibInstaller-Avalonia#402]
After updating WPILib on my ARM Mac with macOS 14.3.1, I get a crash report notification that a `java` executable called by VS Code was killed because it had an invalid code signature. The report doesn't include where the executable is (which is presumably anonymization), so that's all the info I have. Deleting `~/wpilib` before running the installer doesn't cause the issue to appear. 

I had this issue before with the 2024.2.1 installer https://discord.com/channels/176186766946992128/528555967827148801/1204646157847101461, and the same fix worked.

**Comment by ajs256** [comment]
This likely won't happen on an Intel Mac. ARM (Apple silicon) Macs require a signature for all code, even if it's an [ad-hoc signature](https://wiki.lazarus.freepascal.org/Code_Signing_for_macOS#Ad_hoc_signing).

**Comment by sciencewhiz** [comment]
I only have an intel mac, but java is signed on it, so I'm not sure that's the root cause.

**Comment by sciencewhiz** [comment]
I wasn't able to duplicate this on an Apple Silicon Mac with macOS 15.1. I installed WPILIb 2024.2.1 first (to avoid the advantage scope bug), and then installed WPILib 2024.3.2. I was able to build a project after the upgrade.
