### ISSUE TITLE
VS Code doesn't start on Ubuntu 24.04

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/WPILibInstaller-Avalonia#411]
Running on the commandline prints the following:

```
The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/joe/wpilib/2024/vscode/VSCode-linux-x64/chrome-sandbox is owned by root and has mode 4755.
```

I confirmed that setting the ownership and permissions of chrome-sandbox per the message works, but requires root. This has more details and another workaround, but it also requires root and is more invasive (disabling a system wide setting) https://github.com/electron/electron/issues/42510

Running VS Code with the --no-sandbox option also works, and seems like the easiest option. We could modify the frccode<year> bash script.

**Comment by sciencewhiz** [comment]
This also occurs with VS Code 1.92.2 (latest version)

**Comment by sciencewhiz** [comment]
More details here: https://code.visualstudio.com/updates/v1_59#_progress-for-electron-sandbox-support

**Comment by sciencewhiz** [comment]
Another option is to add an apparmor profile, but that also needs root.

The following was adapted from the vscode apparmor profile

```
# This profile allows everything and only exists to give the
# application a name instead of having the label "unconfined"

abi <abi/4.0>,
include <tunables/global>

profile frcvscode /home/**/wpilib/2024/vscode/VSCode-linux-x64/code flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/frccode>
}
```

**Comment by PeterJohnson** [comment]
Seems like the right approach is to add the no-sandbox option to the shortcut we create.

**Comment by sciencewhiz** [comment]
It's probably low risk for us to turn off sandboxing if someone is only using it for our stuff, but they may do more. Maybe we catch that it crashed early and restart with sandboxing disabled rather then always disable sandboxing.

**Comment by sciencewhiz** [comment]
Unfortunately, the script that is used to start VSCode both exits quickly and always has an exit code of 0 even when it crashes, so can't use either time or exit code to detect a problem. One possibility is to use the vscode executable instead of the script in the bin directory. However, that node wouldn't be started with the options set here: https://github.com/microsoft/vscode/blob/main/src/cli.js which looks to include things we use (portable mode)
