### ISSUE TITLE
Tools scripts copies broken on cross builds

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/WPILibInstaller-Avalonia#436]
#433, #434, and #435 use the current OS to determine which scripts to copy. This works in CI since we build each version on the appropriate OS. However, the installer supports cross platform building, so this doesn't work in that case.

Perhaps a better solution would be to test if the files exist, and then do the copy if they do, since scripts/tools.gradle does work properly for cross builds and only makes available the right files.

**Comment by rzblue** [comment]
ToolsUpdater is run during install, not build, so that behavior is fine.
