### ISSUE TITLE
Installer doesn't properly set java home for mac or linux terminals

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/WPILibInstaller-Avalonia#44]
Only windows terminals are set currently.

**Comment by AustinShalit** [comment]
Should the installer be setting JAVA_HOME? It feels like overreach unless we only do it in robot projects.

**Comment by ThadHouse** [comment]
Thats what this does. It sets the JAVA_HOME for the integrated terminal in VS Code. Its just only doing the windows integrated terminals right now.
