### ISSUE TITLE
Choreo doesn't run on Ubuntu 24.04

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/WPILibInstaller-Avalonia#465]
When i run Choreo on Ubuntu 24.04, it fails to run with the following error message:

```
joe@joe-Framework-13th-Gen:~/Downloads$ ~/wpilib/2025/tools/Choreo.sh 
/home/joe/wpilib/2025/choreo/choreo: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
```

Ubuntu 24.04 packages libwebkit2gtk-4.1 rather then 4.0

The installer should either include the required libraries, or package the AppImage version instead of the standalone version, which does bundle the required libraries and runs on Ubuntu 24.04

**Comment by calcmogul** [comment]
Per https://github.com/SleipnirGroup/Choreo/issues/917, bundling the shared libraries was insufficient and took up more space than the AppImage, so we should just use the AppImage.
