### ISSUE TITLE
Wpilib installer showing transparent screen and not responding

### ISSUE THREAD

**Issue by MiracleAig** [wpilibsuite/WPILibInstaller-Avalonia#491]
**Describe the bug**
The wpilib installer window shows up transparent and unresponsive 

**To Reproduce**
1. Install latest wpilib version and mount the iso
2. Open the installer

**Already tried**
1. Installing again
2. Installing the 2025 beta
3. Restarting my PC

**Expected behavior**
The installer window opens but is see through and does not respond, I have to manually end the task for the window to close 

**Screenshots**
![Image](https://github.com/user-attachments/assets/544010a9-0c8f-4792-9429-8c1d32ebfaec)

**Desktop (please complete the following information):**
 - OS: Windows 11 home 24H2, OS build 26100.2605
 - Device: Dell inspirion 16 2 in 1 7640
 - Project Information: Wpilib version 2024.3.2

**Comment by MiracleAig** [comment]
Still having the same issue, and I am using regular windows 11 Home. However, when trying to download on other web browsers like chrome and edge the download always fails citing network issues when my network appears to be fine, but when I download on firefox the download goes fine.

**Comment by MiracleAig** [comment]
Nope, I am using dotnet version 9.

**Comment by Gold856** [comment]
Tthat might be a problem. I'm not sure if the installer is compatible with .NET 9. Try uninstalling it and run the installer again

**Comment by MiracleAig** [comment]
Even when I try and build it via Visual Studio I'm still experiencing the same issue
![Image](https://github.com/user-attachments/assets/64ebddb7-dd6e-435f-86f4-8fa485fe8118)

**Comment by sciencewhiz** [comment]
If you run the installer executable from the command line, is anything printed?

What video card and driver version? I saw an issue opened in the Avalonia repository that sounds similar that was speculated to be video driver issue.

**Comment by MiracleAig** [comment]
I am using a Intel core ultra 7 155H with Intel Arc integrated graphics, the driver version is 32.0.101.6127. Also when running the program I do get a exception in the render loop:

`[Visual] Exception in render loop: 'Avalonia.OpenGL.OpenGlException: eglCreatePbufferFromClientBuffer failed with error EGL_BAD_ATTRIBUTE (0x3004)
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.CreatePBufferFromClientBuffer(Int32 bufferType, IntPtr handle, Int32[] attribs) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 67
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindowSurface.CompositionRenderTarget.BeginDraw()
   at Avalonia.Skia.GlRenderTarget.BeginRenderingSession() in /_/src/Skia/Avalonia.Skia/Gpu/OpenGl/GlRenderTarget.cs:line 63
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer) in /_/src/Skia/Avalonia.Skia/Gpu/SkiaGpuRenderTarget.cs:line 27
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 601
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 374
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 323
   at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render() in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 275
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time) in /_/src/Avalonia.Visuals/Rendering/RenderLoop.cs:line 147' (RenderLoop #30152281)
`

**Comment by PeterJohnson** [comment]
It looks like Avalonia is crashing due to the OpenGL EGL graphics driver returning an error.  Searching around online doesn’t seems to find any reports of this error.  You could try playing around with various installer build options, eg:
```
BuildAvaloniaApp()
        .With(new AvaloniaNativePlatformOptions { UseGpu = !PlatformInfo.IsMacOS })
	.With(new Win32PlatformOptions { UseWgl = true, AllowEglInitialization = false })
```

**Comment by MiracleAig** [comment]
![Image](https://github.com/user-attachments/assets/f50292c2-3007-49c7-8f87-52eaf4dccd4e)
After adding your suggested code. Running the installer in visual studio seems to work fine, but when I actually try and generate the installer I get the same issue with the transparent window.

**Comment by MiracleAig** [comment]
Also supplying the installer with the artifact and resource files, makes the installation run smoothly. However once the installation is finished only some of the installed wpilib tools work, this includes advantage scope, and elastic. The other apps have their generated shortcuts but when I try and open them  windows is not able to find the exe to run

**Comment by MiracleAig** [comment]
It turns out all I needed to do was open the installer with compatibility mode enabled. However, it seems like the issue will persist if your using Intel Arc integrated graphics, because the installer works without issue on my older laptop that has Intel UHD integrated graphics.

**Comment by sciencewhiz** [comment]
> I am using a Intel core ultra 7 155H with Intel Arc integrated graphics, the driver version is 32.0.101.6127

You might try updating your graphics driver. https://www.intel.com/content/www/us/en/download/785597/842655/intel-arc-iris-xe-graphics-windows.html

**Comment by sciencewhiz** [comment]
> However once the installation is finished only some of the installed wpilib tools work, this includes advantage scope, and elastic. The other apps have their generated shortcuts but when I try and open them windows is not able to find the exe to run

This is likely an unrelated issue, Advantage Scope and Elastic install a different way then the other tools. Is it also solved by compatibility mode?

Run `C:\Users\Public\wpilib\2025\jdk\bin\java.exe -jar C:\Users\Public\wpilib\2025\tools\ToolsUpdater.jar` from a commandline and see if it works, or if there's any errors. That's what the installer tried to run to install the tools

**Comment by MiracleAig** [comment]
> Is it also solved by compatibility mode?

Yes, all issues have been resolved after running the installer with compatibility mode for windows 8 enabled .

**Comment by sciencewhiz** [comment]
Can you try this installer and see if it works without using compatibility mode? https://github.com/wpilibsuite/WPILibInstaller-Avalonia/actions/runs/14051034586/artifacts/2812852446
