### ISSUE TITLE
AdvantageScope doesn't launch on Linux

### ISSUE THREAD

**Issue by spacey-sooty** [wpilibsuite/WPILibInstaller-Avalonia#496]
Steps to reproduce:
- run the installer
- try launch advantagescope (through the launcher or directly running AdvantageScope.sh)
- see crash

**Comment by ThadHouse** [comment]
Whats the crash look like? Any error logs? What version of Linux?

**Comment by spacey-sooty** [comment]
> What version of Linux?
Ubuntu 24.04

> Whats the crash look like?
It doesn't even launch you get this message.
```
The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/jadey/wpilib/2025/advantagescope/chrome-sandbox is owned by root and has mode 4755.
```

**Comment by sciencewhiz** [comment]
Did you follow the post-installation instructions? https://docs.wpilib.org/en/latest/docs/zero-to-robot/step-2/wpilib-setup.html#post-installation

**Comment by spacey-sooty** [comment]
Ah nope. This doesn't pop up when you search for AppArmor or sandboxing on the documentation if theres anyway to improve that it would be great

**Comment by sciencewhiz** [comment]
It pops up with both of those search terms for me. Were you searching on latest?

**Comment by spacey-sooty** [comment]
Hm that may have been the issue, i researched on latest and it popped up
