### ISSUE TITLE
UX: Continue button moves

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/WPILibInstaller-Avalonia#79]
The continue button moves around. It should always be in the bottom right. In the example below, the continue button is replaced by the back button.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/3799260/97959233-e29ca900-1d7c-11eb-9661-190301f89c94.png">
<img width="712" alt="image" src="https://user-images.githubusercontent.com/3799260/97959237-e7615d00-1d7c-11eb-8be5-bdb356bae7b9.png">

**Comment by ThadHouse** [comment]
That one actually has to be different. On Windows there is 2 buttons for what to install. There's an option to select between admin and non admin

**Comment by sciencewhiz** [comment]
The 2 buttons could be changed to radio buttons, with a next button.
