### ISSUE TITLE
Cleanup 2020 tools

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/WPILibInstaller-Avalonia#86]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/3799260/98041252-9f2f5280-1def-11eb-8921-b787d0525233.png">

With 2021, the plan is to put the tools into a folder, we should cleanup the 2020 tools and put them in a folder too that way users cannot get confused.

**Comment by ThadHouse** [comment]
This has been done
