### ISSUE TITLE
Create a basic vs advanced install path

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/WPILibInstaller-Avalonia#88]
We should hide some of the installation paths and user options to avoid confusion about what is needed. This path would automatically install everything and download a single instance of VS Code. We can create an advanced button on the start page that then allows users to select what they want to install. 

This is spawned from feedback in **post6706**.

**Comment by sciencewhiz** [comment]
Recommend renaming download vs code for all platforms to download vs code for offline install.

**Comment by ThadHouse** [comment]
We've basically done this. Added a tools only, and an everything option.
