### ISSUE TITLE
Linux tar.gz has files marked executable that don't need to be

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/WPILibInstaller-Avalonia#94]
-rwxr--r-- 1 joe joe    1086704 Nov  2 23:03 libHarfBuzzSharp.so
-rwxr--r-- 1 joe joe     920882 Nov  2 23:03 libMonoPosixHelper.so
-rwxr--r-- 1 joe joe    8541744 Nov  2 23:03 libSkiaSharp.so
-rwxr--r-- 1 joe joe    2416513 Nov  2 23:03 System.Reactive.xml

Feedback from post6733

**Comment by ThadHouse** [comment]
Those are marked executable when they're grabbed from nuget. I don't really want to create a list ones to explicitly changed. We're not doing that from out end.
